### ISSUE TITLE
Cannot connect to Cassandra

### ISSUE THREAD

**Issue by dfeinzimer** [kernelpop/beepboopbackend#15]
`student@tuffix-vm:~$ python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from cassandra.cluster import Cluster
>>> cluster = Cluster()
>>> session = cluster.connect()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cassandra/cluster.py", line 1312, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1348, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 1335, in cassandra.cluster.Cluster.connect
  File "cassandra/cluster.py", line 2863, in cassandra.cluster.ControlConnection.connect
  File "cassandra/cluster.py", line 2906, in cassandra.cluster.ControlConnection._reconnect_internal
cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
>>> 
`

**Comment by dfeinzimer** [comment]
This is on a Tuffix VM, checking now to see if I have the same issue in Ubuntu 18.04

**Comment by dfeinzimer** [comment]
The issue has been resolved. I have Cassandra working in Tuffix now.
